image:
- Visual Studio 2015
clone_depth: 1
install:
- cmd: set PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\usr\bin;%PATH%
build_script:
- cmd: cd src
- cmd: make build ARCH=x86-64-vnni512
- cmd: copy stockfish.exe ..
artifacts:
  - path: stockfish.exe
    name: stockfish
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

