image:
- Visual Studio 2019
clone_depth: 1
install:
- cmd: set PATH=C:\msys64\mingw64\bin;%PATH%
build_script:
- cmd: cd src
- cmd: make build ARCH=x86-64-vnni512
- cmd: copy stockfish.exe ..
artifacts:
  - path: stockfish.exe
    name: stockfish


